COS301-SE-2022/Smart-Hybrid-Workforce-manager

.env, ReadMe.md, db/sql/initdb.sh, db/sql/user/user.credential.function.store.sql, db/sql/user/user.identifier.function.find.sql, db/sql/user/user.identifier.function.store.sql, db/sql/user/user.schema.sql, docker-compose.yml, documentation/api/Smart Hybrid Workforce Manager.postman_collection.json, go/api/ReadMe.md, go/api/data/user.go, go/api/db/db.go, go/api/endpoints/user.go, go/api/go.mod, go/api/go.sum, go/api/main.go, go/api/utils/utils.go, go/lib/go.mod, go/lib/go.sum
This PR closes issues:
#4 
#5 
#6 
#7 
#8
=> ⌨️(feature): Added User Registration

db/sql/initdb.sh, db/sql/team/team.identifier.function.create.sql, db/sql/team/team.schema.sql, db/sql/user/user.schema.sql, documentation/api/Smart Hybrid Workforce Manager.postman_collection.json, go/api/data/team.go, go/api/data/user.go, go/api/endpoints/team.go, go/api/endpoints/user.go, go/api/main.go
This PR Closes:
#19 
#20 
#21 
#22 
#23
=> ⌨️(feature): Added Team Registration Backend

db/sql/initdb.sh, db/sql/team/team.schema.sql, db/sql/user/user.schema.sql
=> 🗃(db): Finished Team Schema

db/sql/mock/mock.sql, db/sql/permission/permission.role.function.find.sql, db/sql/permission/permission.role.function.store.sql, db/sql/permission/permission.user.function.find.sql, db/sql/permission/permission.user.function.store.sql, db/sql/resource/resource.identifier.function.find.sql, db/sql/role/role.identifier.function.find.sql, db/sql/role/role.identifier.function.store.sql, db/sql/role/role.user.function.find.sql, db/sql/role/role.user.function.store.sql, db/sql/team/team.association.function.find.sql, db/sql/team/team.association.function.store.sql, db/sql/team/team.identifier.function.find.sql, db/sql/team/team.user.function.find.sql, db/sql/team/team.user.function.store.sql, db/sql/user/user.credential.function.find.sql, db/sql/user/user.identifier.function.find.sql
Closes #49 
Closes #50 
Closes #51 
Closes #52
=> 🗃(db): Added Store and Find Functions

go/README.md, go/api/data/booking_test.go, go/api/data/team_test.go, go/api/data/user_test.go, go/api/endpoints/booking_test.go, go/api/endpoints/team_test.go, go/api/endpoints/user_test.go, go/api/utils/utils_test.go
Merging into develop so that I can update testing branch
=> 🏗️ (api): Added README containing architecture and blank test files 

go/api/utils/utils_test.go
=> ✅ (api) All tests completed for api/utils

documentation/api/Smart Hybrid Workforce Manager.postman_collection.json, go/api/data/team.go, go/api/endpoints/team.go
=> 📻(api): Added Find Team Endpoint

client/web/ReadMe.md
=> 📝 (client): Added documentation for react testing

client/web/example/src/App.test.js, go/api/endpoints/booking_test.go
=> ✅(api): Added test for bookings.InformationBookingHandler

documentation/api/contract.md, go/api/data/resource.go, go/api/data/user.go, go/api/endpoints/booking.go, go/api/endpoints/permission.go, go/api/endpoints/resource.go, go/api/endpoints/role.go, go/api/endpoints/team.go, go/api/endpoints/user.go, go/api/main.go
Empty endpoints created and can be called
=> :construction: (api) Created endpoints for api

db/sql/permission/permission.role.function.remove.sql, db/sql/permission/permission.user.function.remove.sql, db/sql/role/role.identifier.function.remove.sql, db/sql/role/role.user.function.remove.sql, db/sql/team/team.association.function.remove.sql, db/sql/team/team.user.function.remove.sql, db/sql/user/user.credential.function.remove.sql, db/sql/user/user.identifier.function.remove.sql
=> 🗃(db): Added Remove functions to relations

client/web/example/src/pages/BookingsDesk.js, client/web/example/src/pages/BookingsMeeting.js, db/sql/booking/booking.identifier.function.find.sql, db/sql/booking/booking.identifier.function.remove.sql, db/sql/booking/booking.identifier.function.store.sql, db/sql/booking/booking.schema.sql, db/sql/mock/mock.sql, db/sql/permission/permission.role.function.remove.sql, db/sql/permission/permission.role.function.store.sql, db/sql/permission/permission.user.function.remove.sql, db/sql/permission/permission.user.function.store.sql, documentation/api/Smart Hybrid Workforce Manager.postman_collection.json, go/api/data/booking.go, go/api/data/permission.go, go/api/data/user.go, go/api/endpoints/booking.go, go/api/endpoints/permission.go
Closes #110 
Closes #108 
Started #109
=> 📻(api): Added permission endpoints and updated booking endpoint

db/sql/mock/mock.sql, db/sql/resource/resource.building.function.find.sql, db/sql/resource/resource.building.function.remove.sql, db/sql/resource/resource.building.function.store.sql, db/sql/resource/resource.identifier.function.find.sql, db/sql/resource/resource.identifier.function.remove.sql, db/sql/resource/resource.identifier.function.store.sql, db/sql/resource/resource.room.association.function.find.sql, db/sql/resource/resource.room.association.function.remove.sql, db/sql/resource/resource.room.association.function.store.sql, db/sql/resource/resource.room.function.find.sql, db/sql/resource/resource.room.function.remove.sql, db/sql/resource/resource.room.function.store.sql, db/sql/resource/resource.schema.sql, db/sql/team/team.association.function.store.sql
Closes #114 
Closes #113 
Closes #112 
Closes #107 
Closes #33
Closes #34 
Closes #35 
Continued #107
=> 🗃(db) Added Resource CRUD

db/sql/role/role.identifier.function.remove.sql, db/sql/role/role.user.function.remove.sql, db/sql/team/team.association.function.remove.sql, db/sql/team/team.identifier.function.remove.sql, db/sql/team/team.user.function.remove.sql, db/sql/user/user.credential.function.remove.sql, db/sql/user/user.identifier.function.remove.sql
=> 🗃(db): Updated Remove Functions

db/sql/mock/mock.sql, documentation/api/Smart Hybrid Workforce Manager.postman_collection.json, go/api/data/resource.go, go/api/endpoints/booking.go, go/api/endpoints/permission.go, go/api/endpoints/resource.go, go/api/endpoints/resource_test.go
=> 📻(api): Added Resource endpoints

db/sql/team/team.identifier.function.remove.sql, documentation/api/Smart Hybrid Workforce Manager.postman_collection.json, go/api/data/booking.go, go/api/data/permission.go, go/api/data/resource.go, go/api/data/role.go, go/api/data/team.go, go/api/endpoints/role.go, go/api/endpoints/team.go
=> 📻(api): Added Team and Role endpoints

docker-compose.yml, redis/Dockerfile, redis/README.md
Fixed issue with image not building
=> 🐛 (api) Fixed redis image issue

go/lib/dbmigrate/dbmigrate.go, go/lib/dbmigrate/dbmigrate_example_test.go
Closes #146
The code is somewhat experimental and should be used with caution, as it relies on errors to know when to stop running
=> ✨ (testing) Added auto migration

docker-compose.yml, go/api/go.mod, go/api/go.sum, go/api/main.go, go/api/security/redis.go
Redis is setup and can be integrated with api for authentication
=> :sparkles: (api) Redis setup complete

.gitignore, documentation/api/Smart Hybrid Workforce Manager.postman_collection.json, go/api/data/batch-booking.go, go/api/endpoints/batch-booking.go, go/api/endpoints/batch-booking_test.go, go/api/main.go
Closes #164 
Closes #163
Closes #162
These endpoints still need testing
=> ✨(api) Added BatchBooking endpoints

.env, client/web/example/src/App.css, client/web/example/src/App.js, client/web/example/src/components/BookingTicket/BookingTicket.js, client/web/example/src/pages/BookingsDeskEdit.js, client/web/example/src/pages/CreateBuilding.js, client/web/example/src/pages/CreateDesk.js, client/web/example/src/pages/CreateRoom.js, client/web/example/src/pages/Home.js, client/web/example/src/pages/Resources.js
Closes #166 
Closes #167 
Closes #168 
Closes #169
=> ✨ (ui) Added the editing and deletion of bookings as well as the management of resources

go/api/utils/utils.go, go/api/utils/utils_test.go
=> 🗳(tests): Added utils unit tests

db/sql/user/user.identifier.function.remove.sql, go/api/data/user.go, go/api/endpoints/user.go
=> ✨ (api): Added the user create and remove endpoints

smart_scheduler/room.py
=> ✨ (scheduler) Added room class

smart_scheduler/Dockerfile, smart_scheduler/requirements.txt, smart_scheduler/scheduler_endpoint.py, smart_scheduler/smart_scheduler.py
=> ✨ (scheduler) Added endpoint for scheduler

client/web/example/src/App.css, client/web/example/src/components/BookingTicket/BookingTicket.js, client/web/example/src/components/Team/TeamListItem.js, client/web/example/src/pages/BookingsDesk.js, client/web/example/src/pages/BookingsMeeting.js, client/web/example/src/pages/Home.js, client/web/example/src/pages/Teams.js, client/web/example/src/pages/TeamsCreate.js, client/web/example/src/pages/TeamsEdit.js
Closes #259 
Closes #258 
Closes #257
=> 🪄(ui): Added additional UI elements

client/web/example/src/pages/UsersPermissions.js
=> 🪄(ui): Added and tested user permissions

db/sql/mock/mock.sql, db/sql/resource/resource.room.function.find.sql, db/sql/resource/resource.room.function.store.sql, db/sql/resource/resource.schema.sql, go/api/data/resource.go, go/scheduler/data/data.go
=> 🎺(api+db): Added x, y, z coords to rooms

client/web/example/src/components/BookingForm/DeskBooking.js, go/api/endpoints/booking.go
=> 🩹(fix): Double booking logic

go/api/scheduler/caller.go, go/api/scheduler/data_reciever.go
Added schedulerData to makeBookings to be used by google calender
=> ✨ (api/scheduler) Added schedulerData to makeBookings

.github/workflows/goScheduler.yml, go/api/endpoints/scheduler-invoker.go, go/lib/utils/utils.go, go/scheduler/data/data_test.go, go/scheduler/ga/crossover.go, go/scheduler/ga/fitness.go, go/scheduler/ga/ga.go, go/scheduler/ga/mutate.go, go/scheduler/ga/mutate_test.go, go/scheduler/overseer/overseer.go
=> 🐛(scheduler) Fixed weekly mutate resulting in invalid individuals

go/lib/utils/utils.go, go/lib/utils/utils_test.go, go/scheduler/config.json, go/scheduler/data/data.go, go/scheduler/endpoints/scheduler.go, go/scheduler/ga/fitness.go, go/scheduler/ga/fitness_test.go, go/scheduler/ga/ga.go, go/scheduler/overseer/overseer.go
=> ✨(scheduler) Implemented config file loading

go/api/endpoints/scheduler-invoker.go, go/api/go.mod, go/api/go.sum, go/api/main.go, go/api/scheduler/caller.go, go/api/scheduler/caller_test.go, go/api/scheduler/data_retriever.go, go/api/scheduler/data_retriever_test.go, go/scheduler/config.json, go/scheduler/overseer/overseer.go
Daily and weekly scheduler now gets called periodically
closes #374 
closes #372
=> ✨(scheduler + api) Added buildings groupings to scheduler + periodic calling

go/api/endpoints/scheduler-invoker.go, go/scheduler/ga/fitness.go, go/scheduler/ga/fitness_test.go, go/scheduler/ga/selection.go, go/scheduler/overseer/overseer.go
Also fixed logic with team priorities
closes #371
=> ✨(scheduler) Fixed room spread penalty for daily scheduler

go/api/data/resource.go, go/api/data/resource_test.go, go/api/endpoints/booking.go, go/api/endpoints/scheduler-invoker.go, go/api/main.go, go/api/scheduler/caller.go, go/api/scheduler/data_retriever.go, go/api/security/validate.go, go/lib/collectionutils/sliceutils.go, go/lib/collectionutils/sliceutils_test.go, go/scheduler/config.json, go/scheduler/data/data.go, go/scheduler/data/utils.go, go/scheduler/data/utils_test.go, go/scheduler/endpoints/scheduler.go, go/scheduler/meeting_room/schedule.go, go/scheduler/overseer/overseer.go, python/break.py, python/generate_user.py, python/login.py, python/mock-data-config.json
=> ✨(scheduler) Added meetingroom scheduling functionality
